# Generated by Django 4.1.1 on 2024-01-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=56)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='basket',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='bike',
        ),
        migrations.AddField(
            model_name='bike',
            name='frame',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shop.frame'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.seat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='tire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.tire'),
            preserve_default=False,
        ),
    ]
